### PR TITLE
fix: goroutine leak for tasker

### PR DESCRIPTION
**Pull request by rfyiamcool**
### summary

goroutine leak. 

maybe happen cases:

- if get linux signal, the `ctxdone` goroutine don't exit.
- if get ctx done, the signal goroutine  don't exit.

### CODE REVIEW

**Review by adhocore — COMMENTED** [review]
thanks again. before we merge, i would have to ask issue reproduction steps. 

also are we sure it won't break anything?

**Comment by adhocore** [comment]
btw ctrl+c handling is fixed in #41, does that help the issue this PR relates to?

**Comment by rfyiamcool** [comment]
> btw ctrl+c handling is fixed in #41, does that help the issue this PR relates to?

the #41  pr can't fix the goroutine leak. 😁

**Comment by adhocore** [comment]
ok i see, right now my concern is if it the new changes here would break things or not

**Review by adhocore — COMMENTED** [review]
merging it for now but cant create a release as it has a concern unaddressed

**Pull request merged**
